import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Table from '@mui/material/Table';
import { Button, IconButton, Paper, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField } from '@mui/material';
import * as React from 'react';
import { DataGrid, GridColDef, GridRowsProp } from '@mui/x-data-grid';
import CloseIcon from "@mui/icons-material/Close";
const inter = Inter({ subsets: ['latin'] })

function createData(
  id: number,
  name: string,
  protein: number,
) {
  return { id, name, protein };
}

let rows = [
  createData(0,'Frozen yoghurt', 4.0),
];

const onIconButton = () => {
  delete rows[1];
  setrows(rows);
  alert("aa");
}


export default function Home() {
  const [row, setrows] = React.useState([]);
  return (
    <>
      <Head>
        <title>iTodo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
    
        <TableContainer
  component={Paper} 
  variant="outlined"
>
      <Table sx={{ minWidth: 650 }} aria-label="simple table">
        <TableBody>
          {rows.map((row) => (
            <TableRow
              key={row.id}
              sx={{ '&:last-child td, &:last-child th': { border: 0 } }}
            >
              <TableCell scope="row">{row.name}</TableCell>
              <TableCell align="right">{row.protein}</TableCell>
              <TableCell ><IconButton onClick = {() => {
                rows.forEach((record, index) => {
                  if(record.id == row.id) {                    
                    console.log(record.id);
                    setrows(rows.splice(index, 1));
                  };
                });
                rows.forEach((record) => {
                  console.log(rows);
                });
              }}
                >
              <CloseIcon />
            </IconButton></TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
    <table width="100%">
      <tbody>
        <tr>
        <td><TextField variant="outlined" label="add Todo!" fullWidth id="input" /></td>
        <td width="30">
        <Button variant="contained" onClick={() => {
          setrows(rows.push(createData(rows.length, document.getElementById("input").value,1)));
          document.getElementById("input").value = '';
        }}>Add!</Button>
        </td>
        </tr>
      </tbody>
    </table>
      </main>
    </>
  )
}